In [1]:
from torchvision import models
dir(models)

['AlexNet',
 'AlexNet_Weights',
 'ConvNeXt',
 'ConvNeXt_Base_Weights',
 'ConvNeXt_Large_Weights',
 'ConvNeXt_Small_Weights',
 'ConvNeXt_Tiny_Weights',
 'DenseNet',
 'DenseNet121_Weights',
 'DenseNet161_Weights',
 'DenseNet169_Weights',
 'DenseNet201_Weights',
 'EfficientNet',
 'EfficientNet_B0_Weights',
 'EfficientNet_B1_Weights',
 'EfficientNet_B2_Weights',
 'EfficientNet_B3_Weights',
 'EfficientNet_B4_Weights',
 'EfficientNet_B5_Weights',
 'EfficientNet_B6_Weights',
 'EfficientNet_B7_Weights',
 'EfficientNet_V2_L_Weights',
 'EfficientNet_V2_M_Weights',
 'EfficientNet_V2_S_Weights',
 'GoogLeNet',
 'GoogLeNetOutputs',
 'GoogLeNet_Weights',
 'Inception3',
 'InceptionOutputs',
 'Inception_V3_Weights',
 'MNASNet',
 'MNASNet0_5_Weights',
 'MNASNet0_75_Weights',
 'MNASNet1_0_Weights',
 'MNASNet1_3_Weights',
 'MaxVit',
 'MaxVit_T_Weights',
 'MobileNetV2',
 'MobileNetV3',
 'MobileNet_V2_Weights',
 'MobileNet_V3_Large_Weights',
 'MobileNet_V3_Small_Weights',
 'RegNet',
 'RegNet_X_16GF_Weights'

In [3]:
alexnet = models.AlexNet()

In [5]:
resnet = models.resnet101(pretrained = True)

Downloading: "https://download.pytorch.org/models/resnet101-63fe2227.pth" to /home/meliodas/.cache/torch/hub/checkpoints/resnet101-63fe2227.pth
35.3%


KeyboardInterrupt: 

In [6]:
from torchvision import transforms

preprocess = transforms.Compose([
  transforms.Resize(256),
  transforms.CenterCrop(224),
  transforms.ToTensor(),
  transforms.Normalize(
    mean = [0.485, 0.456, 0.406],
    std = [0.229, 0.224, 0.225]
  )  
])

In [1]:
import torch

a = torch.ones(3)

In [10]:
a[2] = 2
a

tensor([1., 1., 2.])

In [11]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 8.0
points[2] = 5.0
points[3] = 6.0
points[4] = 2.0
points[5] = 1.0

In [12]:
points

tensor([4., 8., 5., 6., 2., 1.])

In [14]:
float(points[0]), float(points[1])

(4.0, 8.0)

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([4., 8., 5., 6., 2., 1.])

In [4]:
points = torch.zeros((3, 2))
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
img_t = torch.randn(3, 5, 5)
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [6]:
batch_t = torch.randn(2, 3, 5, 5)

In [7]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [8]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [9]:
img_gray_weighted_fancy = torch.einsum('...chw, c->...hw', img_t, weights)
batch_gray_weighted_fancy = torch.einsum('...chw, c->...hw', batch_t, weights)
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [10]:
weighted_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])
weighted_named

/tmp/ipykernel_58069/2753219041.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1758.)
  weighted_named = torch.tensor([0.2126, 0.7152, 0.0722], names = ['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [11]:
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named : ", img_named.shape, img_named.names)
print("batch named : ", batch_named.shape, batch_named.names)

img named :  torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named :  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')
